import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("renders the finished Flight Lab website", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>Flight Lab — Throw\. Measure\. Improve\.<\/title>/i);
  assert.match(html, /Measure a throw/i);
  assert.match(html, /Add to Home Screen/i);
  assert.match(html, /No throws yet/i);
  assert.doesNotMatch(html, /Your site is taking shape|codex-preview/i);
});

test("includes all three browser-friendly measuring tools", async () => {
  const page = await readFile(new URL("../app/flight-lab-app.tsx", import.meta.url), "utf8");
  assert.match(page, /Choose a measuring tool/);
  assert.match(page, /Walk & count/);
  assert.match(page, /Outdoor GPS/);
  assert.match(page, /Tape or Measure app/);
  assert.match(page, /Automatic step counting/);
  assert.match(page, /Allow location & set launch point/);
  assert.match(page, /error\.PERMISSION_DENIED/);
  assert.match(page, /error\.TIMEOUT/);
  assert.match(page, /heightDraft/);
  assert.match(page, /You can erase the current number and type any height/);
});

test("requires one top-view airplane photo and can reject invalid images", async () => {
  const page = await readFile(new URL("../app/flight-lab-app.tsx", import.meta.url), "utf8");
  assert.match(page, /top view/i);
  assert.doesNotMatch(page, /Add bottom photo/i);
  assert.doesNotMatch(page, /photos\.bottom/);
  assert.match(page, /inspectPlanePhoto/);
  assert.match(page, /I can’t verify a paper airplane/);
  assert.match(page, /non-airplane photos will be rejected instead of scored/i);
  assert.match(page, /It wobbles side to side/);
  assert.match(page, /It spirals or corkscrews/);
  assert.doesNotMatch(page, /Math\.max\(55/);
});

test("uses on-device shape analysis, plane pictures, and a labeled distance estimate", async () => {
  const page = await readFile(new URL("../app/flight-lab-app.tsx", import.meta.url), "utf8");
  assert.match(page, /inspectPlanePhoto/);
  assert.match(page, /on-device silhouette and fold analyzer/i);
  assert.match(page, /Running on-device shape checks/);
  assert.match(page, /Analyze this plane/);
  assert.match(page, /Estimated next flight/);
  assert.match(page, /Estimate—not a measurement/);
  assert.match(page, /name: "Dart"/);
  assert.match(page, /name: "Glider"/);
  assert.doesNotMatch(page, /Nakamura Lock/);
  assert.doesNotMatch(page, /Paper Dart|Wide Glider/);
  assert.match(page, /Take a picture or choose one/);
  assert.match(page, /\/plane-presets\/dart\.png/);
  assert.match(page, /\/plane-presets\/nakamura-lock\.png/);
});

test("offers a normal Pro upgrade and recognizes the owner account", async () => {
  const page = await readFile(new URL("../app/flight-lab-app.tsx", import.meta.url), "utf8");
  const accessRoute = await readFile(new URL("../app/api/pro-access/route.ts", import.meta.url), "utf8");
  const accessHelper = await readFile(new URL("../app/pro-access.ts", import.meta.url), "utf8");
  const proPage = await readFile(new URL("../app/pro/page.tsx", import.meta.url), "utf8");
  const dashboard = await readFile(new URL("../app/pro/pro-dashboard.tsx", import.meta.url), "utf8");
  const videoLab = await readFile(new URL("../app/pro/pro-video-lab.tsx", import.meta.url), "utf8");
  assert.match(page, /Upgrade to Pro/);
  assert.doesNotMatch(page, />Owner sign in</);
  assert.match(page, /Lifetime Pro is active/);
  assert.match(page, /Pro video lab/);
  assert.match(page, /Video path tracking/);
  assert.match(page, /You will not be charged for Flight Lab Pro/);
  assert.match(page, /signin-with-chatgpt/);
  assert.match(page, /Open Pro video analyzer/);
  assert.match(accessHelper, /FLIGHT_LAB_OWNER_EMAIL/);
  assert.match(accessRoute, /Cache-Control/);
  assert.doesNotMatch(accessHelper, /@gmail\.com|@outlook\.com|@icloud\.com/);
  assert.match(proPage, /getProAccess/);
  assert.match(proPage, /ProDashboard/);
  assert.match(proPage, /redirect\("\/#pro"\)/);
  assert.match(dashboard, /Rate my plane/);
  assert.match(dashboard, /Smart Walk Measure/);
  assert.match(dashboard, /Average distance/);
  assert.match(dashboard, /Newest 5/);
  assert.match(dashboard, /Show all flights/);
  assert.match(dashboard, /flight-lab-v2-throws/);
  assert.match(dashboard, /Experiment Builder/);
  assert.match(dashboard, /Age range · optional/);
  assert.match(dashboard, /This plane&apos;s measured best/);
  assert.match(dashboard, /Your shared hangar/);
  assert.match(dashboard, /＋ Add \{presetId === "dart" \? "Dart" : "Glider"\}/);
  assert.match(dashboard, /flight-lab-v2-planes/);
  assert.match(dashboard, /planesUpdatedEvent/);
  assert.match(dashboard, /activePlaneStorageKey/);
  assert.match(dashboard, /selectPlane/);
  assert.match(dashboard, /deletePlane/);
  assert.match(dashboard, /activeFlightHistory/);
  assert.match(dashboard, /pro-hero-plane-photo/);
  assert.match(videoLab, /accept="video\/\*"/);
  assert.match(videoLab, /analyzeVideo/);
  assert.match(videoLab, /Drag to rotate/);
  assert.match(videoLab, /pinch or scroll to zoom/);
  assert.match(videoLab, /Top map/);
  assert.match(videoLab, /Removing camera shake and false turns/);
  assert.match(videoLab, /turnPenalty/);
  assert.match(videoLab, /forwardFiltered/);
  assert.match(videoLab, /straightness/);
  assert.match(videoLab, /Tracked airtime/);
  assert.match(videoLab, /Flight curve/);
  assert.match(videoLab, /Path stability/);
  assert.match(videoLab, /Relative speed/);
  assert.match(videoLab, /Your video stays on this device/);
});

test("keeps Pro mobile layout vertical and uses full-size controls", async () => {
  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  assert.match(styles, /html \{ max-width: 100%; overflow-x: hidden/);
  assert.match(styles, /html \{[^}]*overscroll-behavior-x: none/);
  assert.match(styles, /\.pro-dashboard \{[\s\S]*?overflow-x: hidden[\s\S]*?overscroll-behavior-x: none[\s\S]*?touch-action: pan-y/);
  assert.match(styles, /\.path-toolbar button \{ min-height: 60px/);
  assert.match(styles, /\.pro-history-tabs button \{ min-height: 64px/);
  assert.match(styles, /\.pro-command-button \{[^}]*min-height: 66px[^}]*font-size: 14px/);
  assert.match(styles, /\.measure-button-row button,[^}]*min-height: 64px[^}]*font-size: 14px/);
  assert.match(styles, /\.pro-dashboard select, \.pro-dashboard input:not\(\.sr-only\) \{[^}]*height: 72px[^}]*font-size: 18px/);
  assert.match(styles, /@media \(max-width: 640px\)[\s\S]*?\.path-toolbar button \{ min-height: 64px[^}]*font-size: 13px/);
  assert.match(styles, /@media \(max-width: 640px\)[\s\S]*?\.pro-dashboard select, \.pro-dashboard input:not\(\.sr-only\) \{ height: 76px/);
  assert.match(styles, /\.pro-plane-panel\.panel-left/);
  assert.match(styles, /\.pro-plane-nose/);
});

test("supports the same no-sign-in Pro Pass route for the dedicated dashboard", async () => {
  const sharePage = await readFile(new URL("../app/pro/share/[token]/page.tsx", import.meta.url), "utf8");
  const dashboard = await readFile(new URL("../app/pro/pro-dashboard.tsx", import.meta.url), "utf8");
  assert.match(sharePage, /FLIGHT_LAB_PRO_SHARE_TOKEN/);
  assert.match(sharePage, /ProDashboard/);
  assert.match(sharePage, /sharedPass/);
  assert.match(dashboard, /Pro Pass active/);
  assert.match(dashboard, /ProVideoLab/);
});

test("adds a conversational, evidence-aware zero-cost Flight Lab Coach", async () => {
  const dashboard = await readFile(new URL("../app/pro/pro-dashboard.tsx", import.meta.url), "utf8");
  const coach = await readFile(new URL("../app/pro/pro-coach-chat.tsx", import.meta.url), "utf8");
  const context = await readFile(new URL("../app/pro/pro-ai-context.ts", import.meta.url), "utf8");
  const videoLab = await readFile(new URL("../app/pro/pro-video-lab.tsx", import.meta.url), "utf8");
  assert.match(dashboard, /ProCoachChat/);
  assert.match(coach, /Talk to Coach/);
  assert.doesNotMatch(coach, /Start voice|SpeechRecognition|webkitSpeechRecognition|speechSynthesis/);
  assert.match(coach, /controlsExpanded/);
  assert.match(coach, /Show more/);
  assert.match(coach, /Show less/);
  assert.match(coach, /coach-extra-controls/);
  assert.match(coach, /What should I improve/);
  assert.match(coach, /What do you like/);
  assert.match(coach, /Tell me more about that/);
  assert.match(coach, /arithmeticReply/);
  assert.match(coach, /one: 1/);
  assert.match(coach, /youtubeSearchUrl/);
  assert.match(coach, /Foldable Flight’s official Arrowhead tutorial/);
  assert.match(coach, /pairedPlaneRecommendation/);
  assert.match(coach, /youtube\.com\/@walshwonders\/videos/);
  assert.match(coach, /C-13 Cobra/);
  assert.match(coach, /Platinum X/);
  assert.match(coach, /Flapping wing paper airplane/);
  assert.match(coach, /Amazing paper airplane dart/);
  assert.match(coach, /one plane from each creator/);
  assert.match(coach, /noopener noreferrer/);
  assert.match(coach, /How’s it going/);
  assert.match(coach, /no upload required/i);
  assert.match(coach, /nextDeviceVariant/);
  assert.match(coach, /recentReplies\.includes/);
  assert.match(coach, /flight-lab-coach-conversation/);
  assert.match(coach, /flight-lab-coach-lessons/);
  assert.match(coach, /previousUser/);
  assert.match(coach, /isFrustrated/);
  assert.match(coach, /Help me learn what went wrong/);
  assert.match(coach, /It didn’t listen/);
  assert.match(coach, /Not helpful\?/);
  assert.match(coach, /rememberLesson/);
  assert.doesNotMatch(coach, /thinkingDelay/);
  assert.match(coach, /thinkingSteps/);
  assert.match(coach, /Checking trusted plane sources/);
  assert.match(coach, /Preparing a careful answer/);
  assert.match(coach, /shouldLookUpKnowledge/);
  assert.match(coach, /coachSearchMode/);
  assert.match(coach, /COACH_MODE_OPTIONS/);
  assert.match(coach, /flight-lab-coach-search-mode/);
  assert.match(coach, /selectedMode === "auto" \? coachSearchMode/);
  assert.match(coach, /Response mode/);
  assert.match(coach, /Coach decides/);
  assert.match(coach, /Always look it up/);
  assert.match(coach, /Never search/);
  assert.match(coach, /aria-pressed/);
  assert.match(coach, /search the browser for/);
  assert.match(coach, /Searching the browser/);
  assert.match(coach, /searchMode/);
  assert.match(coach, /lookUpKnowledge/);
  assert.match(coach, /Searching the browser/);
  assert.match(coach, /explicitlyRequestsLookup/);
  assert.match(coach, /clearlyNeedsFreshInformation/);
  assert.match(coach, /shouldVerifyFacts/);
  assert.match(coach, /world record/);
  assert.match(coach, /Checking built-in knowledge/);
  assert.match(coach, /resolvedKnowledge/);
  assert.match(coach, /Live multi-source search is not connected/);
  assert.match(coach, /askCloudCoach/);
  assert.match(coach, /flightHistory: history/);
  assert.match(coach, /recentFeedback: lessons\.slice/);
  assert.match(coach, /await askCloudCoach/);
  assert.match(coach, /cloudReply\?\.source/);
  assert.match(coach, /COACH_MODEL_OPTIONS/);
  const modelVersions = await readFile(new URL("../app/pro/model-version.ts", import.meta.url), "utf8");
  assert.match(modelVersions, /v40 Gemini/);
  assert.match(modelVersions, /v39 Knowledge/);
  assert.match(modelVersions, /v38 Improved/);
  assert.doesNotMatch(modelVersions, /v37 Classic/);
  assert.match(modelVersions, /flight-lab-coach-model/);
  assert.match(coach, /contextualPlaneRecommendation/);
  assert.match(coach, /recentCoachText/);
  assert.match(coach, /Try this one instead/);
  assert.match(coach, /Cloud AI is optional/);
  assert.match(coach, /selectedModel === "v39"/);
  assert.match(coach, /selectedModel === "v38"/);
  assert.match(coach, /selectedModel === "v40"/);
  assert.match(coach, /Show more/);
  assert.match(coach, /Show less/);
  assert.match(coach, /questionWithoutMode/);
  assert.match(coach, /Built-in knowledge/);
  const knowledge = await readFile(new URL("../app/api/knowledge/route.ts", import.meta.url), "utf8");
  const knowledgeBase = await readFile(new URL("../app/knowledge-base.ts", import.meta.url), "utf8");
  assert.match(knowledge, /findBuiltInAnswer/);
  assert.doesNotMatch(knowledge, /wikipedia/i);
  assert.match(knowledgeBase, /Usain Bolt/);
  assert.match(knowledgeBase, /Florence Griffith-Joyner/);
  assert.match(knowledgeBase, /paper-aircraft flight recognized by Guinness/);
  assert.match(knowledgeBase, /BUILT_IN_ANSWER_COUNT/);
  assert.match(knowledgeBase, /CAPITALS/);
  assert.match(knowledgeBase, /ELEMENTS/);
  assert.match(coach, /Checking your plane history/);
  assert.doesNotMatch(coach, /Open ChatGPT with this scan/);
  assert.doesNotMatch(coach, /https:\/\/chatgpt\.com\//);
  assert.match(coach, /\/api\/pro-coach/);
  const coachRoute = await readFile(new URL("../app/api/pro-coach/route.ts", import.meta.url), "utf8");
  assert.match(coachRoute, /connect it to the previous exchange/);
  assert.match(coachRoute, /value\.slice\(-16\)/);
  assert.match(coachRoute, /role: "developer"/);
  assert.match(coachRoute, /recent user feedback/);
  assert.match(coachRoute, /type: "web_search"/);
  assert.match(coachRoute, /search_context_size: "medium"/);
  assert.match(coachRoute, /corroborate with at least two useful sources/);
  assert.match(coachRoute, /tool_choice: "required"/);
  assert.match(coachRoute, /web_search_call\.action\.sources/);
  assert.match(coachRoute, /X-Flight-Lab-Source/);
  assert.doesNotMatch(coach, /OPENAI_API_KEY|RTCPeerConnection|GPT connected|Offline coach/);
  assert.match(coach, /We can talk normally/i);
  assert.match(context, /flight-lab-local-v2/);
  assert.match(videoLab, /publishProAiContext/);
  assert.match(videoLab, /driftDirection/);
  assert.match(videoLab, /On-device coach observations/);
});

test("offers honest one-photo and six-photo inspections and remembers experiment outcomes", async () => {
  const dashboard = await readFile(new URL("../app/pro/pro-dashboard.tsx", import.meta.url), "utf8");
  const context = await readFile(new URL("../app/pro/pro-ai-context.ts", import.meta.url), "utf8");
  const scanRoute = await readFile(new URL("../app/api/pro-scan/route.ts", import.meta.url), "utf8");
  assert.match(dashboard, /Full inspection/);
  assert.match(dashboard, /Six-angle evidence/);
  assert.match(dashboard, /Quick check/);
  assert.match(dashboard, /one-photo check/i);
  assert.match(dashboard, /id: "underside"/);
  assert.match(dashboard, /id: "tail"/);
  assert.match(dashboard, /Deep visual inspection/);
  assert.match(dashboard, /localViewSignals/);
  assert.match(dashboard, /crossViewScore/);
  assert.match(dashboard, /deepInspection === "used"/);
  assert.match(dashboard, /Deep Visual Inspection could not connect/);
  assert.match(dashboard, /No 3D model or hidden geometry was invented/);
  assert.doesNotMatch(dashboard, /ReconstructedPlaneModel|reconstructPlaneMesh|GuidedVideoScanner|Build shaped 3D model/);
  assert.match(scanRoute, /input_image/);
  assert.match(scanRoute, /detail: "high"/);
  assert.match(scanRoute, /paper_plane_scan/);
  assert.match(scanRoute, /gpt-5\.6-terra/);
  assert.match(scanRoute, /reasoning: \{ effort: "medium" \}/);
  assert.match(scanRoute, /inspectionSummary/);
  assert.match(dashboard, /what happened\?/i);
  assert.match(dashboard, /recordOutcome\("better"\)/);
  assert.match(dashboard, /chooseFreshTest/);
  assert.match(dashboard, /activeThrows/);
  assert.match(context, /CoachTestMemory/);
  assert.match(context, /recommendationId/);
});

test("can select and delete planes without offering individual throw deletion", async () => {
  const page = await readFile(new URL("../app/flight-lab-app.tsx", import.meta.url), "utf8");
  assert.match(page, /function deletePlane/);
  assert.match(page, /item\.planeId !== plane\.id/);
  assert.match(page, /activePlaneStorageKey/);
  assert.match(page, /savedDataLoaded/);
  assert.match(page, /activeThrows\.map/);
  assert.doesNotMatch(page, /activeThrows\.slice\(0, 5\)/);
  assert.match(page, /aria-label={`Delete \$\{plane\.name\}`}/);
  assert.doesNotMatch(page, /function deleteFlight/);
  assert.doesNotMatch(page, /title="Delete this flight"/);
});
